site_name: SimCES
site_url: https://simcesplatform.github.io
site_description: Documentation of Simulation Environment of Complex Energy System (SimCES)
copyright: Copyright &copy; 2021 Tampere University and VTT Technical Research Centre of Finland
docs_dir: markdown
site_dir: docs
extra_css:
    - css/extra.css
theme:
    name: mkdocs
    custom_dir: overrides/

markdown_extensions:
    codehilite:
        use_pygments: False

# See README.txt for the naming convention of files!
nav:
    - Use:
        - Features: core_features.md
        - Installation: core_install.md
        - Run simulation:
            - Overview: core_run.md
            - Test platform:
                - Run first test simulation: core_run-first.md
                - Run Energy Community demo: energy_run-ec-demo.md
            - Configuring settings: core_platform-settings.md
            - Start simulation:
                - Simulation run preparations: core_run-preparations.md
                - Starting a simulation: core_start-simulation.md
            - Follow running simulation: core_follow-run.md
            - Stop simulation: core_stop-simulation.md
        - Log API: core_log-api.md
    - Develop:
        - Overview: core_develop-overview.md
        - Basic concepts:
            - Time and synchronization with epochs: core_time.md
            - Platform-managed and externally managed components: core_cmp-mgmt.md
            - Service-oriented architecture: core_soa.md
        - How to develop:
            - Creating new component:
                - Overview: core_create-cmp.md
                - Building Docker image for a component: core_docker-image.md
                - Creating a component manifest file: core_component-manifest.md
            - Conventions of messaging: core_conv-msg.md
            - Conventions of naming: core_conv-name.md
            - Pseudocode reference: core_pseudocode.md
            - Simulation Tools package:
                - Simulation Tools package: core_sim-tools.md
                - AbstractSimulationComponent: core_abstractsimulationcomponent.md
            - Workflow of component in simulation: core_workflow-sim.md
            - Workflow of start and end: core_workflow-start-end.md
        - Communication:
            - Topics, queues and exchanges: core_topics-queues-exchanges.md
            - Exchange, management: core_exchange-mgmt.md
            - Exchange, simulation-specific: core_exchange-sim.md
            - Topics (core): core_topics.md
            - Reliable messaging in RabbitMQ: core_rabbitmq-reliability.md
            - Footprint of AMQP items: core_amqp-footprint.md
        - Message structures (core):
            - Message structures (core): core_msg.md
            - Message type names (core): core_msgtype.md
            - Units of measure (UCUM): core_ucum.md
            - Message - AbstractMessage: core_msg-abstractmessage.md
            - Message - AbstractResult: core_msg-abstractresult.md
            - Message - Epoch: core_msg-epoch.md
            - Message - SimState: core_msg-simstate.md
            - Message - Start: core_msg-start.md
            - Message - Status: core_msg-status.md
            - Block - Quantity: core_block-quantity.md
            - Block - Quantity array: core_block-quantity-array.md
            - Block - Time series: core_block-time-series.md
        - Platforms internals:
            - Logging system: core_logging-system.md
            - LogWriter: core_logwriter.md
            - Platform Manager: core_platformmanager.md
            - Simulation lifecycle: core_lifecycle.md
            - Simulation Manager: core_simulationmanager.md
            - Dummy Component: core_dummycomponent.md
    - Energy domain:
        - Energy-domain-specific conventions: energy_conventions.md
        - Components (energy):
            - Controller: energy_controller.md
            - Distribution management system (DMS): energy_distribution-management-system-dms.md
            - Grid (DSS): energy_grid-dss.md
            - Economic Dispatch: energy_economicdispatch.md
            - Price Forecaster: energy_priceforecaster.md
            - Procem-LFM: energy_procem-lfm.md
            - Resource Forecaster: energy_resourceforecaster.md
            - Static time series resource: energy_static-time-series-resource.md
            - Storage: energy_storage.md
        - Message structures (energy):
            - ControlState.PowerSetpoint: energy_msg-controlstate-powersetpoint.md
            - DMSNetworkStatus.Current: energy_msg-dmsnetworkstatus-current.md
            - DMSNetworkStatus.Voltage: energy_msg-dmsnetworkstatus-voltage.md
            - FlexibilityNeed: energy_msg-flexibilityneed.md
            - Init.CIS.CustomerInfo: energy_msg-init-cis-customerinfo.md
            - Init.NIS.NetworkBusInfo: energy_msg-init-nis-networkbusinfo.md
            - Init.NIS.NetworkComponentInfo: energy_msg-init-nis-networkcomponentinfo.md
            - LFMMarketResult: energy_msg-lfmmarketresult.md
            - LFMOffering: energy_msg-lfmoffering.md
            - NetworkForecastState.Current: energy_msg-networkforecaststate-current.md
            - NetworkForecastState.Voltage: energy_msg-networkforecaststate-voltage.md
            - NetworkState.Current: energy_msg-networkstate-current.md
            - NetworkState.Loss: energy_msg-networkstate-loss.md
            - NetworkState.Voltage: energy_msg-networkstate-voltage.md
            - Offer: energy_msg-offer.md
            - PriceForecastState: energy_msg-priceforecaststate.md
            - Request: energy_msg-request.md
            - ResourceForecastState.Dispatch: energy_msg-resourceforecaststate-dispatch.md
            - ResourceForecastState.Power: energy_msg-resourceforecaststate-power.md
            - ResourceState: energy_msg-resourcestate.md
            - SelectedOffer: energy_msg-selectedoffer.md
            - Start message blocks: energy_msg-startmessageblocks.md
        - Message type names (energy): energy_msgtype.md
        - Software packages: energy_software-pkg.md
        - Topics (energy):
            - Topics (energy): energy_topics.md
            - PriceForecastState.(MarketId).(ResourceId): energy_topic-priceforecaststate.md
            - ResourceForecastState.(ResourceCategory).(ResourceId): energy_topic-resourceforecaststate.md
            - ResourceState.(ResourceCategory).(ResourceId): energy_topic-resourcestate.md
        - Scenarios:
            - Energy community demo: energy_scenario-ec-demo.md
    - About...:
      - About...: about.md
      - Maintenance plan: maintenance-plan.md
